#!/bin/bash

# character to number
ord() {
  LC_CTYPE=C printf '%d' "'$1"
}

scream_at_file() {
  if [ -d "$1" ]; then
    echo 'Is a directory' && return
  fi

  scream < "$1"
}

scream() {
  # do a "real" checksum
  sha=$(openssl dgst -sha256 <&0)

  # add the character values in the checksum
  sum=0
  for (( i=0; i<${#sha}; i++ )); do
    val=$(ord ${sha:$i:1})
    sum=$(( sum + val ))
  done

  # get a number between 5 and 125
  ayys=$(( $sum % 120 ))
  ayys=$(( $ayys + 5 ))

  # scream into the void
  s=$(printf "%-${ayys}s" "A")
  echo "${s// /A}"
}

case "$#" in
  # if there's no arguments, use stdin
  0)
    scream
  ;;
  # if there's one file as an argument, just scream
  1)
    scream_at_file "$1"
  ;;
  # if there's more than one file argument, scream at all of them
  *)
    for file in "$@"; do
      echo "$file: $(scream_at_file "$file")"
    done
  ;;
esac
